### ISSUE TITLE
NoClassDefFoundError: MessageLogContinuesFactory at PspElfLoader.load(PspElfLoader.kt:67)

### ISSUE THREAD

**Issue by jopadan** [kotcrab/ghidra-allegrex#19]
ghidra/app/util/importer/MessageLogContinuesFactory
java.lang.NoClassDefFoundError: ghidra/app/util/importer/MessageLogContinuesFactory
	at ghidra.app.util.opinion.PspElfLoader.load(PspElfLoader.kt:67)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:369)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:119)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: ghidra.app.util.importer.MessageLogContinuesFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 12 more

---------------------------------------------------
Build Date: 2022-Sep-04 1758 CEST
Ghidra Version: 10.2
Java Home: /opt/openjdk-bin-17.0.3_p7
JVM Version: Eclipse Adoptium 17.0.3
OS: Linux 5.19.6-gentoo amd64

**Comment by kotcrab** [comment]
> Ghidra Version: 10.2

This version is not released yet, so I can't make the plugin compatible with it.

Next time please provide reproduction steps.

**Comment by jopadan** [comment]
To reproduce
- check out, build and install [GHidra](http://github.com/NationalSecurityAgency/ghidra)
- unzip Allegrex-Ghidra-10.1.5.zip to [install location]/Ghidra/Processors/
- execute ./ghidraRun
- Select File -> Import file (decrypted eboot.bin) -> Options -> Select all and image base = 08804000 -> OK

**Comment by kotcrab** [comment]
Thanks but like I said I can't support not yet released Ghidra version. This will fix itself when I update to the new Ghidra.
`Allegrex-Ghidra-10.1.5.zip` is only guarnatted to be compatible with Ghidra 10.1.5. Likewise for other releases.
