### ISSUE TITLE
Upgrade to Ghidra 10.3

### ISSUE THREAD

**Issue by Nemoumbra** [kotcrab/ghidra-allegrex#26]
Is the plugin compatible with the newest Ghidra release?
If not, will this be hard to make a new version like how it happened last time?

**Comment by kotcrab** [comment]
Great work, I'll try to integrate your changes over the weekend.
For relocation status we'll probably use `APPLIED`. 
`CountLeadingOnesOpBehavior` and `CountLeadingZerosOpBehavior` were replaced by native [pcode instructions](https://github.com/NationalSecurityAgency/ghidra/blob/2daddb7d7c2ffda98a4efa8ea49ba5c6c0a98fc6/Ghidra/Processors/MIPS/data/languages/mips32Instructions.sinc#L981-L990).

**Comment by kotcrab** [comment]
Thanks @CB9001 I added your commit as a patch so you are contributed.

**Comment by kotcrab** [comment]
Released [v16](https://github.com/kotcrab/ghidra-allegrex/releases/tag/v16).

**Comment by Nemoumbra** [comment]
I've got the same error log as here: https://github.com/kotcrab/ghidra-allegrex/issues/19

```ghidra/app/util/importer/MessageLogContinuesFactory
java.lang.NoClassDefFoundError: ghidra/app/util/importer/MessageLogContinuesFactory
	at ghidra.app.util.opinion.PspElfLoader.load(PspElfLoader.kt:67)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:809)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:100)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:388)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:347)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: ghidra.app.util.importer.MessageLogContinuesFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 12 more

---------------------------------------------------
Build Date: 2023-May-12 1514 CEST
Ghidra Version: 10.3
Java Home: /usr/lib/jvm/java-17-openjdk
JVM Version: N/A 17.0.7
OS: Linux 5.15.114-2-MANJARO amd64
```

This may be indicative of the fact that bumping the version up for Ghidra_10.3.1 was a mistake. Can you please investigate?

**Comment by kotcrab** [comment]
You are most likely using wrong plugin version, update to a release compatible with your Ghidra version: https://github.com/kotcrab/ghidra-allegrex/releases if that doesn't help please create new issue with reproduction steps.

**Comment by Nemoumbra** [comment]
False alert, I mistakenly thought that "ghidra-10.3-1" meant 10.3.1 and downloaded the wrong plugin version.
By the way, can I contact you in Discord to discuss the beta feature of PPSSPP remote debugging?

**Comment by kotcrab** [comment]
You most likely downloaded v15 looking at the stack trace.

No, sorry, I try to keep DMs for friends only for various reasons. We can either talk in some public channel if it's suitable or I've enabled [discussions](https://github.com/kotcrab/ghidra-allegrex/discussions) here.
